[package]
name = "fortress"
version = "0.1.0"
edition = "2024"
description = "A simple password manager CLI application"
authors = ["Blaxxmith", "Axxiar"]

[[bin]]
name = "frtrs"
path = "src/main.rs"

[dependencies]
